
openapi: 3.0.0
info:
  title: Custom Agent Toolkit API
  version: 1.0.0
paths:
  /notion/update:
    post:
      summary: Update a Notion page
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                page_id:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: Notion page updated
  /telegram/send:
    post:
      summary: Send a Telegram message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chat_id:
                  type: string
                message:
                  type: string
      responses:
        '200':
          description: Message sent
